### ISSUE TITLE
no init.rst7 file and -mden flag

### ISSUE THREAD

**Issue by xhxuInChina** [njzjz/dprc-tutorial#1]
Dear Zeng:
  I have tyied dprc-tutorial. But when run the command below, i found you didn't provide init.rst7. Would you please add it ?
  
sander -O -p ETP_ETH.parm7 -c init.rst7 -i low_level_md.mdin -o rc.mdout -r init_-1.50.rst7 -x mndod.nc -inf rc.mdinfo -ref init.rst7 -frc mndod.mdfrc -mden mndod.mden
 
 What's more, the output flag of mden file is '-e' in amber22 mannual. Why did you use '-mden' ?
 Thanks for you time.

**Comment by njzjz** [comment]
The command was fixed in #2.
